In [1]:
import pandas as pd
import numpy as np

path = r"C:/Users/cbi7088/NCAA2020"

In [2]:
#### Preparing Training data for tourney result ####

tourney_result = pd.read_csv(path+'/MDataFiles_Stage1/MNCAATourneyCompactResults.csv')
tourney_seed = pd.read_csv(path+'/MDataFiles_Stage1/MNCAATourneySeeds.csv')
tourney_result = tourney_result.drop(['DayNum', 'WScore', 'LScore', 'WLoc', 'NumOT'], axis=1)
tourney_result = pd.merge(tourney_result, tourney_seed, left_on=['Season', 'WTeamID'], right_on=['Season', 'TeamID'], how='left')
tourney_result.rename(columns={'Seed':'WSeed'}, inplace=True)
tourney_result = tourney_result.drop('TeamID', axis=1)
tourney_result = pd.merge(tourney_result, tourney_seed, left_on=['Season', 'LTeamID'], right_on=['Season', 'TeamID'], how='left')
tourney_result.rename(columns={'Seed':'LSeed'}, inplace=True)
tourney_result = tourney_result.drop('TeamID', axis=1)

tourney_result

Season  WTeamID  LTeamID WSeed LSeed
0       1985     1116     1234   X09   X08
1       1985     1120     1345   Z11   Z06
2       1985     1207     1250   W01   W16
3       1985     1229     1425   Y09   Y08
4       1985     1242     1325   Z03   Z14
...      ...      ...      ...   ...   ...
2246    2019     1120     1246   Y05   Y02
2247    2019     1277     1181   W02   W01
2248    2019     1403     1277   X03   W02
2249    2019     1438     1120   Z01   Y05
2250    2019     1438     1403   Z01   X03

[2251 rows x 5 columns]

In [3]:
#### Preparing training data to make seeds int ####

def get_seed(x):
    return int(x[1:3])

tourney_result['WSeed'] = tourney_result['WSeed'].map(lambda x: get_seed(x))
tourney_result['LSeed'] = tourney_result['LSeed'].map(lambda x: get_seed(x))

tourney_result

Season  WTeamID  LTeamID  WSeed  LSeed
0       1985     1116     1234      9      8
1       1985     1120     1345     11      6
2       1985     1207     1250      1     16
3       1985     1229     1425      9      8
4       1985     1242     1325      3     14
...      ...      ...      ...    ...    ...
2246    2019     1120     1246      5      2
2247    2019     1277     1181      2      1
2248    2019     1403     1277      3      2
2249    2019     1438     1120      1      5
2250    2019     1438     1403      1      3

[2251 rows x 5 columns]

In [4]:
#### Preparing training data ####
#Split season result into df for all game wins, df for all game losses, then concat dfs to show total points scored in season

season_result = pd.read_csv(path+'/MDataFiles_Stage1/MRegularSeasonCompactResults.csv')
season_win_result = season_result[['Season', 'WTeamID', 'WScore']]
season_lose_result = season_result[['Season', 'LTeamID', 'LScore']]
season_win_result.rename(columns={'WTeamID':'TeamID', 'WScore':'Score'}, inplace=True)
season_lose_result.rename(columns={'LTeamID':'TeamID', 'LScore':'Score'}, inplace=True)
season_result = pd.concat((season_win_result, season_lose_result)).reset_index(drop=True)
season_score = season_result.groupby(['Season', 'TeamID'])['Score'].sum().reset_index()

C:\Users\cbi7088\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:4223: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(**kwargs)


In [5]:
#### Preparing training data ####
# Merging tourney result df with season score df

tourney_result = pd.merge(tourney_result, season_score, left_on=['Season', 'WTeamID'], right_on=['Season', 'TeamID'], how='left')
tourney_result.rename(columns={'Score':'WScoreT'}, inplace=True)
tourney_result = tourney_result.drop('TeamID', axis=1)
tourney_result = pd.merge(tourney_result, season_score, left_on=['Season', 'LTeamID'], right_on=['Season', 'TeamID'], how='left')
tourney_result.rename(columns={'Score':'LScoreT'}, inplace=True)
tourney_result = tourney_result.drop('TeamID', axis=1)

tourney_result

Season  WTeamID  LTeamID  WSeed  LSeed  WScoreT  LScoreT
0       1985     1116     1234      9      8     2156     2092
1       1985     1120     1345     11      6     2040     1728
2       1985     1207     1250      1     16     2045     1907
3       1985     1229     1425      9      8     1933     1915
4       1985     1242     1325      3     14     2281     1824
...      ...      ...      ...    ...    ...      ...      ...
2246    2019     1120     1246      5      2     2682     2532
2247    2019     1277     1181      2      1     2680     2839
2248    2019     1403     1277      3      2     2339     2680
2249    2019     1438     1120      1      5     2299     2682
2250    2019     1438     1403      1      3     2299     2339

[2251 rows x 7 columns]

In [6]:
#### Preparing training data ####
# New df containing Seed Diff, Score Diff, and tourney game result

tourney_win_result = tourney_result.drop(['Season', 'WTeamID', 'LTeamID'], axis=1)
tourney_win_result.rename(columns={'WSeed':'Seed1', 'LSeed':'Seed2', 'WScoreT':'ScoreT1', 'LScoreT':'ScoreT2'}, inplace=True)

tourney_lose_result = tourney_win_result.copy()
tourney_lose_result['Seed1'] = tourney_win_result['Seed2']
tourney_lose_result['Seed2'] = tourney_win_result['Seed1']
tourney_lose_result['ScoreT1'] = tourney_win_result['ScoreT2']
tourney_lose_result['ScoreT2'] = tourney_win_result['ScoreT1']

tourney_win_result['Seed_diff'] = tourney_win_result['Seed1'] - tourney_win_result['Seed2']
tourney_win_result['ScoreT_diff'] = tourney_win_result['ScoreT1'] - tourney_win_result['ScoreT2']
tourney_lose_result['Seed_diff'] = tourney_lose_result['Seed1'] - tourney_lose_result['Seed2']
tourney_lose_result['ScoreT_diff'] = tourney_lose_result['ScoreT1'] - tourney_lose_result['ScoreT2']

tourney_win_result['result'] = 1
tourney_lose_result['result'] = 0
tourney_result = pd.concat((tourney_win_result, tourney_lose_result)).reset_index(drop=True)

tourney_result

Seed1  Seed2  ScoreT1  ScoreT2  Seed_diff  ScoreT_diff  result
0         9      8     2156     2092          1           64       1
1        11      6     2040     1728          5          312       1
2         1     16     2045     1907        -15          138       1
3         9      8     1933     1915          1           18       1
4         3     14     2281     1824        -11          457       1
...     ...    ...      ...      ...        ...          ...     ...
4497      2      5     2532     2682         -3         -150       0
4498      1      2     2839     2680         -1          159       0
4499      2      3     2680     2339         -1          341       0
4500      5      1     2682     2299          4          383       0
4501      3      1     2339     2299          2           40       0

[4502 rows x 7 columns]

In [7]:
#### Prepare test data ####

test_df = pd.read_csv(path +'/MSampleSubmissionStage1_2020.csv')

In [8]:
#### Prepare test data ####

test_df['Season'] = test_df['ID'].map(lambda x: int(x[:4]))
test_df['WTeamID'] = test_df['ID'].map(lambda x: int(x[5:9]))
test_df['LTeamID'] = test_df['ID'].map(lambda x: int(x[10:14]))

test_df

ID  Pred  Season  WTeamID  LTeamID
0      2015_1107_1112   0.5    2015     1107     1112
1      2015_1107_1116   0.5    2015     1107     1116
2      2015_1107_1124   0.5    2015     1107     1124
3      2015_1107_1125   0.5    2015     1107     1125
4      2015_1107_1129   0.5    2015     1107     1129
...               ...   ...     ...      ...      ...
11385  2019_1449_1459   0.5    2019     1449     1459
11386  2019_1449_1463   0.5    2019     1449     1463
11387  2019_1458_1459   0.5    2019     1458     1459
11388  2019_1458_1463   0.5    2019     1458     1463
11389  2019_1459_1463   0.5    2019     1459     1463

[11390 rows x 5 columns]

In [9]:
#### Prepare test data ####

test_df = pd.merge(test_df, tourney_seed, left_on=['Season', 'WTeamID'], right_on=['Season', 'TeamID'], how='left')
test_df.rename(columns={'Seed':'Seed1'}, inplace=True)
test_df = test_df.drop('TeamID', axis=1)
test_df = pd.merge(test_df, tourney_seed, left_on=['Season', 'LTeamID'], right_on=['Season', 'TeamID'], how='left')
test_df.rename(columns={'Seed':'Seed2'}, inplace=True)
test_df = test_df.drop('TeamID', axis=1)
test_df = pd.merge(test_df, season_score, left_on=['Season', 'WTeamID'], right_on=['Season', 'TeamID'], how='left')
test_df.rename(columns={'Score':'ScoreT1'}, inplace=True)
test_df = test_df.drop('TeamID', axis=1)
test_df = pd.merge(test_df, season_score, left_on=['Season', 'LTeamID'], right_on=['Season', 'TeamID'], how='left')
test_df.rename(columns={'Score':'ScoreT2'}, inplace=True)
test_df = test_df.drop('TeamID', axis=1)

test_df

ID  Pred  Season  WTeamID  LTeamID Seed1 Seed2  ScoreT1  \
0      2015_1107_1112   0.5    2015     1107     1112   W14   Z02     2096   
1      2015_1107_1116   0.5    2015     1107     1116   W14   Z05     2096   
2      2015_1107_1124   0.5    2015     1107     1124   W14   Z03     2096   
3      2015_1107_1125   0.5    2015     1107     1125   W14   W15     2096   
4      2015_1107_1129   0.5    2015     1107     1129   W14  W11a     2096   
...               ...   ...     ...      ...      ...   ...   ...      ...   
11385  2019_1449_1459   0.5    2019     1449     1459   Y09   Y07     2374   
11386  2019_1449_1463   0.5    2019     1449     1463   Y09   W14     2374   
11387  2019_1458_1459   0.5    2019     1458     1459   Z05   Y07     2279   
11388  2019_1458_1463   0.5    2019     1458     1463   Z05   W14     2279   
11389  2019_1459_1463   0.5    2019     1459     1463   Y07   W14     2436   

       ScoreT2  
0         2599  
1         2653  
2         2212  
3         2287  
4         2166  
...        ...  
11385     2436  
11386     2265  
11387     2436  
11388     2265  
11389     2265  

[11390 rows x 9 columns]

In [10]:
#### Prepare test data ####

test_df['Seed1'] = test_df['Seed1'].map(lambda x: get_seed(x))
test_df['Seed2'] = test_df['Seed2'].map(lambda x: get_seed(x))
test_df['Seed_diff'] = test_df['Seed1'] - test_df['Seed2']
test_df['ScoreT_diff'] = test_df['ScoreT1'] - test_df['ScoreT2']
test_df = test_df.drop(['ID', 'Pred', 'Season', 'WTeamID', 'LTeamID'], axis=1)
test_df

Seed1  Seed2  ScoreT1  ScoreT2  Seed_diff  ScoreT_diff
0         14      2     2096     2599         12         -503
1         14      5     2096     2653          9         -557
2         14      3     2096     2212         11         -116
3         14     15     2096     2287         -1         -191
4         14     11     2096     2166          3          -70
...      ...    ...      ...      ...        ...          ...
11385      9      7     2374     2436          2          -62
11386      9     14     2374     2265         -5          109
11387      5      7     2279     2436         -2         -157
11388      5     14     2279     2265         -9           14
11389      7     14     2436     2265         -7          171

[11390 rows x 6 columns]

In [11]:
#### Create model ####

import matplotlib.pyplot as plt  

from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import GridSearchCV
from sklearn import metrics

from sklearn.ensemble import RandomForestRegressor


import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

%matplotlib inline

In [12]:
#### Create model ####
# Create train and test set from training data

scaler = StandardScaler()
#scaled_data = scaler.fit_transform(tourney_result)

X = tourney_result.drop('result', axis=1)
y = tourney_result.result

X = scaler.fit_transform(X)

seed = 12

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= seed)

In [13]:
#### Create model ####
# Pick a model

model = LogisticRegression(random_state=seed)
#model = RandomForestRegressor(random_state = seed)


model.fit(X_train, y_train)
#predictions = model.predict_proba(X_test)[:, 1]
predictions = model.predict(X_test)

In [14]:
#### Create model ####

print('X_train shape: ',X_train.shape)
print('y_train shape: ',y_train.shape)
print('X_test shape: ',X_test.shape)
print('y_test shape: ',y_test.shape)
print('predictions shape: ', predictions.shape)
print('Model Score: ', model.score(X_test, y_test))
print(model.coef_)

X_train shape:  (3601, 6)
y_train shape:  (3601,)
X_test shape:  (901, 6)
y_test shape:  (901,)
predictions shape:  (901,)
Model Score:  0.7114317425083241
[[-0.37041615  0.43066157  0.1136691  -0.07627386 -0.49172912  0.13928368]]


In [15]:
X_test

array([[ 0.6842734 , -0.82921565,  0.04762607, -0.40994531,  0.92903175,
         0.3355335 ],
       [-1.26164109, -0.61300293, -1.1443666 ,  0.89355635, -0.39815646,
        -1.4943929 ],
       [ 1.33291157, -1.26164109, -0.09848916,  1.70872553,  1.59262585,
        -1.32521635],
       ...,
       [ 0.25184796,  0.46806068,  0.02455524, -0.16001136, -0.13271882,
         0.13534124],
       [ 1.76533701, -1.04542837, -0.01389613,  0.51288772,  1.72534468,
        -0.38628647],
       [ 0.25184796, -1.26164109, -0.48684806,  1.29345066,  0.92903175,
        -1.30547908]])

In [26]:
from sklearn import model_selection
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

kfold = model_selection.KFold(n_splits=7, random_state=seed)
scoring = 'accuracy'
results = model_selection.cross_val_score(model, X, y, cv=kfold, scoring=scoring)
print(scoring, ': ', 'Mean: ', results.mean().round(4), 'Stdev: ', results.std().round(4))

matrix = confusion_matrix(y_test, predictions)
print(matrix)

report = classification_report(y_test, predictions)
print(report)

accuracy :  Mean:  0.6075 Stdev:  0.037
[[341 129]
 [131 300]]
              precision    recall  f1-score   support

           0       0.72      0.73      0.72       470
           1       0.70      0.70      0.70       431

    accuracy                           0.71       901
   macro avg       0.71      0.71      0.71       901
weighted avg       0.71      0.71      0.71       901

